### ISSUE TITLE
An answer to your first "type oddity question"

### ISSUE THREAD

**Issue by jvoigtlaender** [niksilver/elm-explained#1]
https://github.com/niksilver/elm-explained/blob/master/types/TypeQuestions.md#oddity-unused-variables

That's something you won't see in user code. The two modules you point to are "internal" modules of the Elm standard library, that come with native (JavaScript) implementations. That is, the `Array` and `Signal` types are implemented with JavaScript constructs that don't have a counterpart on the Elm side. The strange definitions you point out are just placeholders, so that the Elm compiler does not choke (it has to see _something_). So these are dirty tricks that are played in `core`, but that won't happen in pure Elm modules/packages. In fact, there were (are?) proposals for forbidding the presence of unused type variables in type definitions in "normal" modules.

**Comment by jvoigtlaender** [comment]
Actually, for type aliases, it already _is_ forbidden by the compiler. Try this:

``` elm
type alias Foo a = Int
```

For non-alias type definitions, there are use cases (you may want to have a look at https://wiki.haskell.org/Phantom_type), but such tricks are a bit frowned upon in Elm (but are popular in Haskell).

Anyway, the specific cases of `Array` and `Signal` are yet different, since the reason for those is as in my previous comment.

**Comment by niksilver** [comment]
Thanks a lot, @jvoigtlaender. I've now updated the text with https://github.com/niksilver/elm-explained/commit/3b26f0fd537c21aabdef971fed4e774819930cbd
